### PR TITLE
Output the sarif file location

### PR DESCRIPTION
**Pull request by clarkbw**
This creates a new output called `sarif` for the location of the sarif file.  This will if the file name or location were to change due to the environment of the Action. If users only refer to the file as an output from your action the location string can change without their knowing.

With this change CI configuration looks like this:

```yaml
name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Container image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - uses: anchore/scan-action@v2
      id: scan
      with:
        image: "localbuild/testimage:latest"
        acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
```

`anchore/scan-action@v2` requires an `id` now and I've used the `scan` id here. That `id: scan` enables the output to be available as `${{ steps.scan.outputs.sarif }}` and fed to the next step.

### CODE REVIEW

**Comment by zhill** [comment]
Thanks @clarkbw. I like this approach better. Will review and merge if it looks good

**Comment by zhill** [comment]
@clarkbw can you rebase or merge master in? Looks like an interleaved merge has created a conflict. Thanks!

**Comment by clarkbw** [comment]
> @clarkbw can you rebase or merge master in? Looks like an interleaved merge has created a conflict. Thanks!

Happy to rebase!

**Comment by alfredodeza** [comment]
@clarkbw this is really good, thanks for making the changes. I verified that this is also backwards compatible, which is great - so that we don't force users to make this change.

**Pull request merged**
