### PR TITLE
Include process environment into grype execution

### PR DESCRIPTION
**Pull request by erhan-**
Adds the current process environment variables to the grype process. Useful for proxy variables.

Might fix https://github.com/anchore/scan-action/issues/197

### CODE REVIEW

**Comment by kzantow** [comment]
@erhan- I had a slightly different thing in mind (the same idea, just not modifying the `process.env`) -- I've also added a test, would you mind if I push these changes here?

**Comment by erhan-** [comment]
Please push and change however you think is best. It works now.

**Comment by kzantow** [comment]
Also: it looks like you'll need to [sign-off the commits](https://github.com/anchore/scan-action/blob/main/CONTRIBUTING.md#sign-off-your-work), would you be able to do this?

**Comment by kzantow** [comment]
Also: I'm looking in to these test failures, I'm pretty sure they are unrelated to this change...

**Comment by kzantow** [comment]
@erhan- could you verify the current state of this PR is still working for you? If so, I can probably get this rebased, merged, and released for you.

(Also it would be good to know if `HTTPS_PROXY` works vs. the lowercase `https_proxy`)

**Comment by erhan-** [comment]
Sorry, I never added a sign-off commit before. I hereby also confirm that the code si for your project and I dont claim any rights.

I cant that test unfortunately if upper and lowercase work at the moment but I think I read something that we should use the lowercase one. It works and is the first time I got any results. Thanks for your help!

**Review by kzantow — APPROVED** [review]

**Pull request merged**
