### PR TITLE
Add exitCode to action output

### PR DESCRIPTION
**Pull request by rolandsusans**
expose grype exitCode to action output

### CODE REVIEW

**Comment by alfredodeza** [comment]
Thanks for contributing a PR for this @rolandsusans ! Would you mind helping me understand in what context the exit code would be useful to report?

**Comment by njimenezotto** [comment]
Hi,
Thanks for your work. 
The exit code will be very useful to run under the same job different security tools and only fail the workflow at the end if any of the tools ended in failure.

**Comment by luhring** [comment]
Hi @njimenezotto — I want to make sure I understand. A failure in any step should trigger a failure of the job. What would be the value added by exposing the exit code? A specific example would be helpful if you have one!

**Comment by operatorequals** [comment]
The Exit code can be checked adhoc (at any step of the workflow - e.g. the last).

**Comment by kzantow** [comment]
Hi, I think this can be accomplished using the GitHub `continue-on-error` property. E.g you could set up a workflow like this:

```yaml
- uses: anchore/scan-action@v3
  id: scan
  continue-on-error: true
  ...
- run: exit 1
  if: ${{steps.scan.outcome == 'failure'}}
```

See the step object: https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context

And an example here:
https://github.com/kzantow-anchore/sbom-action-test/blob/scan-test/.github/workflows/scan-test.yml

And the failing run:
https://github.com/kzantow-anchore/sbom-action-test/runs/3805645839?check_suite_focus=true

I'll add an issue to update the documentation with an example like this, but going to close this PR because I think it is not needed -- feel free to reopen if I have misunderstood the use case!

**Pull request closed without merging**
