### PR TITLE
fix undefined items message when scanning containers

### PR DESCRIPTION
**Pull request by alfredodeza**
Example output with the fix:

```
|           "ruleId": "ANCHOREVULN_CVE-2016-2779_deb_libsmartcols1_2.25.2-6",
|           "ruleIndex": 0,
|           "level": "error",
|           "message": {
|             "text": "The container image contains software with a vulnerability: (libsmartcols1 type=deb)",
|             "id": "default"
|           },
```

Not sure why the compiled `index.js` now has a ton of changes :/

### CODE REVIEW

**Review by zhill — COMMENTED** [review]
Looks good but also looks like there may be other places where form may be the older v.package. Is there a bunch of code that can be removed to make it all more clear between the non-grype and grype methods?

**Comment by alfredodeza** [comment]
> Looks good but also looks like there may be other places where form may be the older v.package. Is there a bunch of code that can be removed to make it all more clear between the non-grype and grype methods?

You are right, there is a lot of dead code, I can go ahead and cleanup those and remove normalize the functions to avoid the `grype_` prefix. Can I get those in a follow-up PR? We could go ahead and cut a version with this fix while I get to the rest of the cleanup.

**Comment by alfredodeza** [comment]
@zhill any feedback here? Do you want me to proceed with fully cleaning up instead?

**Comment by zhill** [comment]
> @zhill any feedback here? Do you want me to proceed with fully cleaning up instead?

Yes, another PR is fine :+1:

**Pull request merged**
