### PR TITLE
Add only-fixed option

### LINKED ISSUE #133: Integration of only-fixed function in the action
Actually seems that there isn't a way to use `--only-fixed` functionality that is integrated on official grype release but, I thinks is really useful because for me is useless have a notification, maybe with a medium or higher security level that i can't fix because it doesn't exist a fixed package.
I tried to integrate directly grype commands on my workflow but it have no possibility to create acs report.
Have you any suggestions?

### PR DESCRIPTION
**Pull request by lucacome**
Adds support for `--only-fixed` flag

Closes #133

### CODE REVIEW

**Review by kzantow — APPROVED** [review]
Thanks for the contribution -- LGTM!

**Comment by kzantow** [comment]
@lucacome something went a little wonky with the tests -- are you able to have a look at this?

**Comment by lucacome** [comment]
@kzantow just pushed an update, missed some tests. Seems like I'm not really able to run them locally, I get some weird errors...so I need to rely on the pipeline 🙂

**Comment by kzantow** [comment]
If you have Docker locally, you should be able to run the test fairly easily. See: https://github.com/anchore/scan-action/tree/main/tests#developing-tests

**Pull request merged**
